// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fabizsohkxhaccrvgkjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhYml6c29oa3hoYWNjcnZna2p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzk0MjUsImV4cCI6MjA2NTg1NTQyNX0.box7WXuNxexcBhE4JqA9--hL0Vw4OSBn9aANR6KRRK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);